<a href="https://colab.research.google.com/github/TirendazAcademy/Hugging-Face-Tutorials/blob/main/Pratical-NLP-with-Tranformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Installing Transformers

In [ ]:
# !pip install -q transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 22.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 25.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 26.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 52.4 MB/s eta 0:00:00

In [1]:
from transformers import pipeline

# Sentiment Analysis

In [2]:
classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [3]:
text = "It's great to learn NLP for me"
classifier(text)

[{'label': 'POSITIVE', 'score': 0.999805748462677}]

In [4]:
import pandas as pd
outputs = classifier(text)
pd.DataFrame(outputs)

      label     score
0  POSITIVE  0.999806

# Zero-Shot Classification

In [5]:
classifier = pipeline("zero-shot-classification")

No model was supplied, defaulted to facebook/bart-large-mnli and revision d7645e1 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [6]:
text = "This is a tutorial about Hugging Face"
labels = ["tech", "education", "business"]
outputs = classifier(text, labels)
pd.DataFrame(outputs)

                                sequence     labels    scores
0  This is a tutorial about Hugging Face  education  0.869358
1  This is a tutorial about Hugging Face       tech  0.113720
2  This is a tutorial about Hugging Face   business  0.016922

# Text Generation

In [7]:
generator = pipeline("text-generation")

No model was supplied, defaulted to openai-community/gpt2 and revision 607a30d (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [8]:
prompt= "This tutorial will walk you through how to"
outputs = generator(prompt)
print(outputs)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

[{'generated_text': 'This tutorial will walk you through how to use a C++ class to create a user interface to the "Tick in the Wall" app. To begin with, we\'ll create a "Tick in the Wall" app in Visual Studio.\n\nWe\'ll start by creating a new class called "Tick". It\'s a simple class that you will use to interface to your app. We\'ll extend it into a class called "TickManager".\n\nWe\'ll create the following class for our "TickManager". It\'s named "TickManager" and is a simple class that we\'ll write our application to.\n\nclass Tick<Tick, Window, Window> { public: // An interface that is used to create a TickManager public: // The TickManager class // that holds the current tick with the current location in our UI public: // An interface that we will use in the context of our application public: // The TickManager class // will hold the current tick in the location of our app public: // The TickManager class // will hold the current tick in the position of our app public: // The TickManager class // will hold the current tick in the position of the application in our UI public: // TickManager class // will hold the current tick in the position'}]

In [9]:
outputs = generator(prompt, max_length=50)
print(outputs[0]["generated_text"])

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

This tutorial will walk you through how to set up a Node.js application using Node.js.

To start with Node.js, install the latest release of node.js and build it in the browser.

Install Node.js

To install Node.js, first install node.js by running:

npm install -g

Then run the following command:

npm install @nodejs

This will produce the following output:

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 node < script src = "https://github.com/nodejs/node-js.js/blob/master/node-js-2.2.js" ></ script > < script src = "https://github.com/nodejs/node-js.js/blob/master/node-js-2.2.js" > </ script >

Before you start, create a file called node-js-2.2.js that contains the following changes:

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 node < script src = "https://github.com/

## Text generation with distilgpt2

In [10]:
generator = pipeline("text-generation", model="distilgpt2")

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cuda:0

In [11]:
outputs = generator(prompt, max_length=50)
print(outputs[0]["generated_text"])

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

This tutorial will walk you through how to use a video game in a game.


Video game development
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The Video Game Development Tutorial
The

# Named Entity Recognition (NER)

In [12]:
ner = pipeline("ner", grouped_entities=True)

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cuda:0
/usr/local/lib/python3.12/dist-packages/transformers/pipelines/token_classification.py:186: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="AggregationStrategy.SIMPLE"` instead.
  warnings.warn(

In [13]:
text = "My name is Tirendaz from Turkey. HuggingFace is a nice platform"
outputs = ner(text)
pd.DataFrame(outputs)

  entity_group     score         word  start  end
0          PER  0.997805     Tirendaz     11   19
1          LOC  0.999806       Turkey     25   31
2          ORG  0.807525  HuggingFace     33   44

# Question-Answering

In [14]:
reader = pipeline("question-answering")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [15]:
text = "My name is Tirendaz and I love Berlin"
quenstion = "Where do I like"
outputs = reader(question=quenstion, context=text)
pd.DataFrame([outputs])

      score  start  end  answer
0  0.923865     31   37  Berlin

# Summarization

In [16]:
summarizer = pipeline("summarization")

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [17]:
text = """James Stephen Donaldson[b] (born May 7, 1998), known professionally as MrBeast (or Jimmy Donaldson), is an American YouTuber, entrepreneur and philanthropist. He is credited with pioneering a genre of YouTube videos that centers on expensive stunts and challenges.[12] With over 184 million subscribers as of September 18, 2023,[13] he is the most-subscribed individual user on the platform and the second-most-subscribed channel overall,[14][15] and has ranked on the Forbes list for the highest paid YouTube creator in 2022.[16]

Donaldson grew up in Greenville, North Carolina. He began posting videos to YouTube in early 2012, at the age of 13,[17] under the handle MrBeast6000. His early content ranged from Let's Plays to "videos estimating the wealth of other YouTubers".[18] He went viral in 2017 after his "counting to 100,000" video earned tens of thousands of views in just a few days, and he has become increasingly popular ever since, with most of his videos gaining tens of millions of views.[18] His videos, typically involving challenges and giveaways, became increasingly grand and extravagant.[19] Once his channel took off, Donaldson hired some of his childhood friends to co-run the brand. As of 2023, the MrBeast team is made up of over 250 people, including Donaldson himself.[20][21] Other than MrBeast, Donaldson runs the YouTube channels Beast Reacts, MrBeast Gaming, MrBeast 2 (formerly MrBeast Shorts),[22] and the philanthropy channel Beast Philanthropy.[23][24] He formerly ran MrBeast 3 (initially MrBeast 2), which is now inactive.[25][26] As of 2023, he is the highest paid YouTuber,[27] and has an estimated net worth of $500 million.[28]

Donaldson is the founder of MrBeast Burger and Feastables; and a co-creator of Team Trees, a fundraiser for the Arbor Day Foundation that has raised over $23 million;[29][30] and Team Seas, a fundraiser for Ocean Conservancy and The Ocean Cleanup that has raised over $30 million.[31] Donaldson won the Creator of the Year award four times at the Streamy Awards in 2020, 2021, 2022, and 2023; he also won the Favorite Male Creator award twice at the Nickelodeon Kids' Choice Awards in 2022 and 2023. In 2023, Time magazine named him as one of the world's 100 most influential people. """

In [18]:
outputs = summarizer(text, max_length=60, clean_up_tokenization_spaces = True)
print(outputs[0]["summary_text"])

 James Stephen Donaldson, known as MrBeast, is an American YouTuber, entrepreneur and philanthropist. He is credited with pioneering a genre of YouTube videos that centers on expensive stunts and challenges. With over 184 million subscribers as of September 18, 2023, he is the most

# Translation

In [19]:
translator = pipeline("translation_en_to_de")

No model was supplied, defaulted to google-t5/t5-base and revision a9723ea (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [20]:
text = "I hope you enjoy it"
outputs = translator(text, clean_up_tokenization_spaces = True)
print(outputs[0]["translation_text"])

Ich hoffe, Sie genießen es

Let's connect [YouTube](http://youtube.com/tirendazacademy) | [Medium](http://tirendazacademy.medium.com) | [Twitter](http://twitter.com/tirendazacademy) | [Instagram](https://www.instagram.com/tirendazacademy) | [GitHub](http://github.com/tirendazacademy) | [Linkedin](https://www.linkedin.com/in/tirendaz-academy) | [Kaggle](https://www.kaggle.com/tirendazacademy) 😎